import { Link } from "react-router-dom";
import usePageMetadata from "../hooks/usePageMetadata";

export default function TermsPage() {
  usePageMetadata({
    title: "Terms of Use | VEIL",
    description: "Terms of use and acceptable usage policy for VEIL.",
    path: "/terms",
  });

  return (
    <main className="site-shell">
      {/* NAVBAR */}
      <nav className="navbar">
        <Link to="/" className="brand" aria-label="VEIL Home">
          <div className="brand-mark">V</div>
          <div>
            <div className="brand-name">VEIL</div>
            <div className="brand-subtitle">Supervisory Intelligence for SOC Assessment</div>
          </div>
        </Link>
        <div className="nav-links">
          <Link to="/upload">Analyze</Link>
          <Link to="/dashboard">Overview</Link>
        </div>
      </nav>

      <section className="intro-section" style={{ paddingBottom: "40px", borderBottom: "none" }}>
        <div className="section-label">LEGAL & COMPLIANCE</div>
        <div className="intro-content" style={{ gridTemplateColumns: "1fr" }}>
          <h1 style={{ fontSize: "clamp(36px, 4.4vw, 62px)", margin: 0, letterSpacing: "-0.045em" }}>Terms of Use</h1>
          <p style={{ maxWidth: "800px", marginTop: "20px" }}>
            By using the VEIL platform, you agree to these Terms of Use. VEIL is an analytical tool designed for security operations oversight and is not a replacement for primary threat detection infrastructure.
          </p>
        </div>
      </section>

      <section className="capabilities-section" style={{ paddingTop: "40px" }}>
        <div className="capability-grid">
          <article className="capability" style={{ minHeight: "auto", padding: "40px 0" }}>
            <div className="capability-number">01</div>
            <div>
              <h3>Acceptable Use</h3>
              <p style={{ maxWidth: "800px" }}>
                VEIL must be used strictly for authorized supervisory, auditing, and assessment purposes. Users may only upload data they have explicit authorization to analyze. Reverse engineering, malicious probing, or using the platform for unauthorized surveillance is strictly prohibited.
              </p>
            </div>
          </article>
          
          <article className="capability" style={{ minHeight: "auto", padding: "40px 0" }}>
            <div className="capability-number">02</div>
            <div>
              <h3>Evidence-Backed Analytics Disclaimer</h3>
              <p style={{ maxWidth: "800px" }}>
                VEIL provides risk signals and evidence-backed findings based on the data provided. These signals are statistical and heuristic interpretations. They do not constitute a guaranteed detection of security incidents, nor do they represent definitive security verdicts.
              </p>
            </div>
          </article>
          
          <article className="capability" style={{ minHeight: "auto", padding: "40px 0" }}>
            <div className="capability-number">03</div>
            <div>
              <h3>Human Review Disclaimer</h3>
              <p style={{ maxWidth: "800px" }}>
                All findings generated by VEIL require human review. The platform is designed to augment human supervisors, not replace them. Users must independently verify findings before taking administrative, technical, or punitive actions against entities.
              </p>
            </div>
          </article>

          <article className="capability" style={{ minHeight: "auto", padding: "40px 0" }}>
            <div className="capability-number">04</div>
            <div>
              <h3>Limitation of Liability</h3>
              <p style={{ maxWidth: "800px" }}>
                The maintainers of VEIL provide this software "as-is" without warranties of any kind. Under no circumstances shall the maintainers be liable for missed threats, operational downtime, or decisions made based on the platform's outputs.
              </p>
            </div>
          </article>

          <article className="capability" style={{ minHeight: "auto", padding: "40px 0" }}>
            <div className="capability-number">05</div>
            <div>
              <h3>Future Updates</h3>
              <p style={{ maxWidth: "800px" }}>
                These Terms of Use may be updated over time to reflect changes in platform capabilities or regulatory requirements. Continued use of the platform indicates acceptance of any revised terms.
              </p>
            </div>
          </article>
        </div>
      </section>

      {/* FOOTER */}
      <footer className="footer">
        <div>
          <strong>VEIL</strong>
          <span>Supervisory Intelligence for SOC Assessment</span>
        </div>
        <div className="footer-meta">
          <Link to="/privacy">Privacy Policy</Link>
          <Link to="/terms">Terms of Use</Link>
          <Link to="/security">Security</Link>
        </div>
      </footer>
    </main>
  );
}
